api_version = "2024-10"
uid = "f13f5303-0e14-0ee5-27c3-678fd7bc694bc5ab036e"
type = "theme_app_extension"
name = "kova-chat-widget"

[[theme_extension.blocks]]
type = "kova-chat"
name = "Kova AI Chat Widget"
file = "blocks/kova-chat.liquid"
