name = "naay-chat-widget-v22"
uid = "883590b0-86fe-caf7-d093-094950d1939586da09d4"
type = "theme_app_extension"
api_version = "2025-10"

[application]
embedded = true

[[app_blocks]]
type = "naay-chat"
name = "Naay AI Chat Widget"
files = ["blocks/naay-chat.liquid"]